services:
  app:
    build:
        dockerfile: DockerFile
    image: php:8.1-fpm
    container_name: medileave_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  webserver:
    image: nginx:stable
    container_name: medileave_webserver
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: medileave_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: W3m1l3ave@4202
      MYSQL_DATABASE: madileave
      MYSQL_USER: userMedileave
      MYSQL_PASSWORD: W3m1l3ave@2024
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:

